import './globals.css';

import { FC, PropsWithChildren } from 'react';
import { Noto_Sans_KR } from 'next/font/google';

import Header from './Header';

const NotoSansKR = Noto_Sans_KR({
  weight: ['400', '700'],
  subsets: ['latin'],
  preload: true,
});

const metadata = {
  title: 'Next.js Awesome Memo App',
  description: 'Generated by create next app',
}

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="ja">
      <body className={NotoSansKR.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}

export default RootLayout;
export { metadata };
